### ISSUE TITLE
Структурная минификация шортхендов

### ISSUE THREAD

**Issue by kizu** [css/csso#101]
Про шортхенды уже было, но не уверен, что было такое (чем-то похоже на #58, но точно безопасно). Скажем, есть вот такой CSS:

``` CSS
.some_class_a{font:10px/1.5 Helvetica,Arial,sans-serif}
.some_class_b{font:12px/1.5 Helvetica,Arial,sans-serif}
.some_class_c{font:14px/1.5 Helvetica,Arial,sans-serif}
.some_class_d{font:16px/1.5 Helvetica,Arial,sans-serif}
```

В нём записи почти одинаковые, различается только часть без font-family. Если вынести часть с font-family вот так: 

``` CSS
.some_class_a{font:10px/1.5 a}
.some_class_b{font:12px/1.5 a}
.some_class_c{font:14px/1.5 a}
.some_class_d{font:16px/1.5 a}
.some_class_a,.some_class_b,.some_class_c,.some_class_d{
    font-family: Helvetica,Arial,sans-serif;
}
```

То подобная запись будет уже заметно короче. Т.е. иногда в шортхендах могут быть длинные повторяющиеся последовательности, которые можно минимизировать.

Тут важно, что в данном случае нужно в оригинальном шортхенде оставлять _какой-то_ font-family, в данном случае `a` — без него запись не сработает, но т.к. дальше оно всё-равно переопределяется, то что там будет — совершенно не важно, главное, чтобы коротко.

Подозреваю, что подобное может срабатывать и для многих других шортхендов, но часто будет ли экономия будет зависеть как от количества одинаковой информации, так и от длинны селекторов (ну, как и с остальными структурными минификациями).
