### ISSUE TITLE
The order of selectors in a group doesn't matter

### ISSUE THREAD

**Issue by kizu** [css/csso#106]
Look at those to examples:

``` CSS
.class1,.class2{a:b}
.class2{c:d}
```

and

``` CSS
.class2,.class1{a:b}
.class2{c:d}
```

The first one would be minified to `.class1{a:b}.class2{a:b;c:d}`, but the second won't — it would give just `.class2,.class1{a:b}.class2{c:d}`.

In CSS the order of selectors in groups don't matter, so it would be safe to minimize the second case there too.
