### ISSUE TITLE
Overridden properties and structure minification

### ISSUE THREAD

**Issue by kizu** [css/csso#108]
This is something that can be done sometimes and something that is totally safe.

When there is some selector with some properties somewhere, then those properties can be used somewhere before with any values, so it could be used to merge selectors in some cases.

Here is an example:

``` CSS
.class1,
.class2 {
    width: 10px;
    height: 10px;
}

.class3 {
    width: 10px;
}

.class4 {
    width: 20px;
}

.class3 {
    height: 20px;
}
```

In that case we can't merge two `.class3` rules, 'cause there is `.class4` between them. But! we can safely move the first `.class3` selector to the first rule, even while it have set height — because later it's height is overridden anyway.

So, in ideal case, that could be minified to `.class1,.class2,.class3{width:10px;height:10px}.class4{width:20px}.class3{height:20px}`.
