### ISSUE TITLE
Не удаляются перекрывающиеся свойства

### ISSUE THREAD

**Issue by zemd** [css/csso#113]
После сборки файла stylus-ом пропускаю через csso. Вроде бы оптимизации есть, но остаются такие вот вещи:

```css
.cssclass {
  vertical-align: top;
  padding: 0 12px;
  vertical-align: middle
}
```

Хотя если пропустить отдельно это свойство - то всё отлично удаляется.

Подскажите пожалуйста, какая возможная проблема может быть?
