### ISSUE TITLE
Небезопасная структурная минимизация для сочетания "фоновых" свойств в полной и короткой записи

### ISSUE THREAD

**Issue by bivihoba** [css/csso#115]
В чем-то перекликается с #58, но смысл другой немного.
Структурная минимизация ломает правильную последовательность свойств при сочетании конкретных правил для фона и укороченной записи.
Реальный случай кнопки на цсс3 с полным фолбеком для ИЕ на картинках.
"Лишние" свойства удалены:

``` css
.b-billet_viewtype_a1-right-arrow {
  background-image: url('../images/bg/billets_original.png');
  background-position: 0 -100px;
  background: linear-gradient(to bottom, transparent 0%, transparent 100%);
}
.b-billet_viewtype_a1-right-arrow .b-billet__in {
  background-image: url('../images/bg/billets_original.png');
  background-position: 100% -125px;
  background: linear-gradient(to bottom, #fbfbfb 0%, #e4e6e8 100%);
}
```

На выходе:

``` css
.b-billet_viewtype_a1-right-arrow {
    background-position: 0 -100px;
    background: linear-gradient(to bottom, transparent 0, transparent 100%);
}

.b-billet_viewtype_a1-right-arrow, .b-billet_viewtype_a1-right-arrow .b-billet__in {
    background-image: url('../images/bg/billets_original.png');
}

.b-billet_viewtype_a1-right-arrow .b-billet__in {
    background-position: 100% -125px;
    background: linear-gradient(to bottom, #fbfbfb 0, #e4e6e8 100%);
}
```

Т.е. современные браузеры получают лишнее правило (и лишний запрос к серверу):

``` css
.b-billet_viewtype_a1-right-arrow {
    background-image: url('../images/bg/billets_original.png');
}
```
