### ISSUE TITLE
CSSO не объеденяет несоседние свойства

### ISSUE THREAD

**Issue by robhrt7** [css/csso#127]
CSSO не объеденяет свойства селекторов, если они не стоят друг за другом, в первом примере всё ок, во втором не работает.

Вход

``` css
.class-v1 {
    width: 100%;
    height: 100%;
    font-size: 10px;
    border: 1px solid;
    margin: auto;
    position: absolute;
    }

.class-v2 {
    width: 100%;
    height: 100%;
    font-size: 10px;
    border: 1px solid;
    margin: auto;
    position: absolute;
    padding: 10px;
}
```

Выход

``` css
.class-v1,.class-v2{width:100%;height:100%;font-size:10px;border:1px solid;margin:auto;position:absolute}
.class-v2{padding:10px}
```

Вход

``` css
.class-v1 {
    width: 100%;
    height: 100%;
    font-size: 10px;
    border: 1px solid;
    margin: auto;
    position: absolute;
    }

.classsad { width: 10px;}

.class-v2 {
    width: 100%;
    height: 100%;
    font-size: 10px;
    border: 1px solid;
    margin: auto;
    position: absolute;
    padding: 10px;
}
```

Выход

``` css
.class-v1{width:100%;height:100%;font-size:10px;border:1px solid;margin:auto;position:absolute}
.classsad{width:10px}
.class-v2{width:100%;height:100%;font-size:10px;border:1px solid;margin:auto;position:absolute;padding:10px}
```

Фича или баг?
