### ISSUE TITLE
Optimize overlapping styles in media queries

### ISSUE THREAD

**Issue by apaatsio** [css/csso#130]
Overlapping styles inside media queries should be minimized.

``` css
.foo {
  margin: 0;
}
@media (max-width: 768px) {
  .foo {
    margin: 0;
  }
}
```

could be minimized to

``` css
.foo {
  margin: 0;
}
```
