### ISSUE TITLE
@-moz-document crashes csso

### ISSUE THREAD

**Issue by drewwells** [css/csso#137]
Rules like this cause csso to fail completely

    @-moz-document url-prefix() {
        span
        {
            padding:12px 10px 12px 10px;
        }
    }

**Comment by ben-eb** [comment]
```css
@-moz-document url-prefix() {
    .live-chat.help .main span {
        padding: 12px 10px 12px 10px;
    }
 }
```

=>

```css
@-moz-document url-prefix(){.live-chat.help .main span{padding:12px 10px}}
```

I don't think it's CSSO's job to rectify invalid input.
