### ISSUE TITLE
Incorrect minification of margin short-hand

### ISSUE THREAD

**Issue by jcoglan** [css/csso#139]
The following:

```css
#footer {
  margin: 20px auto;
  margin-top: 32px;
}

p {
  padding: 0;
}

#footer {
  margin-bottom: 11px;
}
```

Incorrectly minifies to:

```css
#footer{margin-top:32px}p{padding:0}#footer{margin-bottom:11px}
```

If the `padding` rule is replaced with a `color` rule, we get:

```css
p{color:#000}#footer{margin:32px auto 11px}
```

This is correct. What is it about `padding` (and other certain CSS properties) that cause the first example to be incorrectly optimised?
