### ISSUE TITLE
keyframes

### ISSUE THREAD

**Issue by silentroach** [css/csso#14]
Будет отлично если CSSO научится понимать keyframe

``` css
#button_account_add.pulsate img {
    -webkit-animation-name: pulsate;
    -webkit-animation-duration: 1s;
    -webkit-animation-timing-function: ease-in-out;
    -webkit-animation-iteration-count: infinite;
    }
    @-webkit-keyframes pulsate {
        0% {
            opacity: .5;
            }
        50% {
            opacity: 1;
            }
        100% {
            opacity: .5;
            }
        }
```

Спасибо за отличный продукт!
