### ISSUE TITLE
Background rewrites background-position

### ISSUE THREAD

**Issue by ai** [css/csso#143]
In:

``` css
.test1 {
  background: url(/1.png) no-repeat;
  background-size: 85px 85px;
}
.test2 {
  background: url(/2.png) no-repeat;
  background-size: 85px 85px;
}
```

Out:

``` css
.test1{background:url(/1.png)}
.test1,.test2{background-size:85px 85px}
.test2{background:url(/2.png)}
```

So in out third line `background` for `.test2` rewrites `background-size`, which was combined for `.test1` and `.test2`.

**Comment by ArturAralin** [comment]
@ai what was expected?

CSSO has combined are common properties

`.test1,.test2{background-size:85px 85px}
.test1{background:url(/1.png) no-repeat}
.test2{background:url(/2.png) no-repeat}`

**Comment by lahmatiy** [comment]
@ArturAralin `background-size` will be lost in this case, since `background` reset all `background-*` properties

**Comment by ArturAralin** [comment]
@lahmatiy in this case how need to do it?

**Comment by lahmatiy** [comment]
In this case

```css
.test1{background:url(/1.png) no-repeat}
.test2{background:url(/2.png) no-repeat}
.test1,.test2{background-size:85px 85px}
```
