### ISSUE TITLE
Ошибка в сжатии background (IE 7, IE 8)

### ISSUE THREAD

**Issue by dchusovitin** [css/csso#16]
``` css
.node {
    background:url('img/image.png')  no-repeat;
}
```

После сжатия:

``` .node{background:url('img/image.png')no-repeat}```

Сочетание "')no-repeat" вызывает ошибку и правило не обрабатывается (IE 7, IE 8)
Если поставить пробел после скобки, то все работает.
```
