### ISSUE TITLE
Do not remove overridden fonts

### ISSUE THREAD

**Issue by tadatuta** [css/csso#161]
````css
html {
  font-size: 62.5%;
}
body {
  font-size: 16px;
  font-size: 1.6rem;
}
h1 {
  font-size: 20px;
  font-size: 2rem;
}
````
