### ISSUE TITLE
Multiple namespaces turn into one after processing

### ISSUE THREAD

**Issue by 1999** [css/csso#174]
```css
@namespace html url("http://www.w3.org/1999/xhtml");
@namespace islands url("http://bar.yandex.ru/ui/islands");

.test {
	color: red;
	margin: 0px;
}
```

```$ ~/node_modules/csso/bin/csso --restructure-off test.css``` outputs:

```css 
@namespace html url("http://www.w3.org/1999/xhtml");.test{color:red;margin:0}
```
