### ISSUE TITLE
Bug in padding collapse

### ISSUE THREAD

**Issue by doochik** [css/csso#175]
input CSS

```css
.bar
{
    padding: 20px 0 10px 46px;
}

.bar
{
    padding-bottom: 15px;
}

.any-selector
{
    padding: 3px 5px;
}

.bar
{
    padding-top: 0;
}

```

Output CSS
```css
.bar{padding-bottom:15px}
.any-selector{padding:3px 5px}
.bar{padding-top:0}
```

Expected result:
```css
.bar{padding: 20px 0 15px 46px;}
.any-selector{padding:3px 5px}
.bar{padding-top:0}
```
