### ISSUE TITLE
Bug: CSSO don't optimize multiple colors when one of them is converted to a keyword

### ISSUE THREAD

**Issue by kizu** [css/csso#176]
``` CSS
a {
  color: #00f;
  color: #f00;
}
```

is minified to 

``` CSS
a{color:#00f;color:red}
```

If you'll run CSSO once again after this, you'll get proper

``` CSS
a{color:red}
```
