### ISSUE TITLE
filter AlphaImageLoader

### ISSUE THREAD

**Issue by eGavr** [css/csso#182]
This

```

.a {
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='x', sizingMethod="y");
}

.a {
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='y', sizingMethod="z");
}

```

can be minimized to

```

.a{filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='y', sizingMethod="z")}

```

**Comment by lahmatiy** [comment]
Those values should be in quotes.

```css
.a {
    filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(src='x', sizingMethod='y')";
}
.a {
    filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(src='y', sizingMethod='z')";
}
```

In this case `csso` works correctly

```css
.a{filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='y', sizingMethod='z')"}
```
