### ISSUE TITLE
Critical bug: overriden property breaks free

### ISSUE THREAD

**Issue by kizu** [css/csso#186]
When you have a property that was overriden inside one block and then you have the overriden property inside another block, they become merged before this property is removed from the first block. Right now CSSO would convert this:

``` CSS
.foo {
  display: inline-block;
  display: block;
}
.bar {
  display: inline-block;
}
```

to this:

``` CSS
.foo{display:block}.foo,.bar{display:inline-block}
```

You can see the `.foo` in the second selector. This way, according to the rules' order, it would win and the computed CSS would change after CSSO.

**Comment by zackcote** [comment]
:+1:  yeah, this is a major one. hopefully it gets fixed.

**Comment by kaelig** [comment]
Not sure it's related but I've had this:

```css
/* input */
.responsive {
  padding-left: 5px;
  padding-right: 5px;
  float: left;
  box-sizing: border-box;
  display: none;
  display: block;
  width: 66.6666666667%;
  display: block;
  width: 66.6666666667%;
  display: block;
  width: 33.3333333333%;
  display: block;
  width: 33.3333333333%;
}

/* Output */
.responsive{display:block;display:block;display:block;display:block;width:33.3333333333%}
```

I'm surprised it keeps all of these `display:block`…

**Comment by lahmatiy** [comment]
@kizu current output is

```css
.foo{display:block}.bar{display:inline-block}
```

@kaelig for your example, output is

```css
.responsive{padding-left:5px;padding-right:5px;float:left;box-sizing:border-box;display:block;width:33.3333333333%}
```

Looks like problem is solved.
