### ISSUE TITLE
Wrong optimization with !important

### ISSUE THREAD

**Issue by lahmatiy** [css/csso#189]
Input:
```css
.foo { margin: 0 !important }
.foo { margin: 1px }
```
Result:
```css
.foo { margin: 1px }
```
Expected:
```css
.foo { margin: 0 !important }
```
