### ISSUE TITLE
Escaped zero-plus sequence in selector gets broken

### ISSUE THREAD

**Issue by borodean** [css/csso#191]
As far as you know, `+` has a special meaning in CSS. So if you want to have it plainly in a selector you should escape it with a slash. Pretty same thing is with numbers -- if you want to have them at the beginning of an identifier you should escape them with a slash and a corresponding charcode. [Futher reading](http://mathiasbynens.be/notes/css-escapes).

Here are the selectors with escaped `10+`, `15+` and `20+` class names:

```css
.\31 0\+,
.\31 5\+,
.\32 0\+ {
  color: red;
}
```

All the browsers I've tested down to IE5 recognize those selectors perfectly. However, after the code above gets cssoed, those which end with a zero lose their escaped plus characters and practically become targeting towards `10` and `20` class names:

```css
.\31 0,.\31 5\+,.\32 0{color:red}
```
