### ISSUE TITLE
/*! exclaimation-comments need to be kept */

### ISSUE THREAD

**Issue by tomByrer** [css/csso#194]
One of the tricks to reducing HTTP requests, reducing redundant CSS rules, & increasing GZip compressibility, is to concoct (merge) several CSS files together.  Often the top-line comment that is marked with an exclamation point `/*! */` is a typical use for contact, version, & copyright information.  Some licenses require that those notifications stay with all files & versions, but CSSO removes them if they are [not the top-line](https://github.com/css/csso/commit/4e3cd2403064413bde85a2a4ce58e75ae29821db).

Can all  `/*! */` comments remain please?  Before:
```css
 /*! first.css, MIT license */
/* will be removed */
.test {
  color: red
}
 /*! second.css, (c) different author, Apache 2.0 License */
/* will be removed */
.next {
  color: green
}
```
Expected after:
`/*! first.css, MIT license */.test{color:red}/*! second.css, (c) different author, Apache 2.0 License */.next{color:green}`

Current result, [breaking license section 4](http://www.apache.org/licenses/LICENSE-2.0)
`/*! first.css, MIT license */.test{color:red}.next{color:green}`
