### ISSUE TITLE
Fail restructuring similar blocks

### ISSUE THREAD

**Issue by silentroach** [css/csso#196]
Input:

```css
.support-question .closed {
    background: url('/s/a/i/ic/util.gif') no-repeat transparent top right;
    background-position: right -65px;
    white-space: nowrap;
    padding-right: 15px;
}
.support-question .opened {
    background: url('/s/a/i/ic/util.gif') no-repeat transparent top right;
    background-position: right -450px;
    white-space: nowrap;
    padding-right: 15px;
}
```

After CSSO:

```css
.support-question .closed {
    background-position:right -65px
}
.support-question .closed, .support-question .opened {
    background:url('/s/a/i/ic/util.gif') no-repeat top right;
    white-space:nowrap;
    padding-right:15px
}
.support-question .opened {
    background-position:right -450px
}
```

Position for closed is overriden with default values :{

**Comment by silentroach** [comment]
new hope!

**Comment by lahmatiy** [comment]
It's similar to #143, but examples could be useful for tests.

**Comment by lahmatiy** [comment]
Current output for first example:

```css
.support-question .closed,.support-question .opened {
    background: url('/s/a/i/ic/util.gif') no-repeat top right;
    white-space: nowrap;
    padding-right: 15px
}

.support-question .closed {
    background-position: right -65px
}

.support-question .opened {
    background-position: right -450px
}
```

It's correct. But because of good enough declaration position.
Second example is still fail...
