### ISSUE TITLE
Bug with CSS Animations

### ISSUE THREAD

**Issue by Chaptykov** [css/csso#197]
It copies [this issue](https://github.com/css/csso/issues/80), but bug wasn't fixed.
I use latest versions of `csso` and `grunt-csso`.

Before:

```css
@keyframes fadein {
    0% {
        opacity: 0;
        transform: scale(.95);
        }
    30% {
        opacity: 1;
        transform: scale(1);
        }
    70% {
        opacity: 1;
        transform: scale(1);
        }
    100% {
        opacity: 1;
        transform: scale(1);
        opacity: 0;
        }
    }
```

After:

```css
@keyframes fadein {
    0% {
        opacity: 0;
        transform: scale(.95)
    }

    30%,70% {
        opacity: 1
    }

    30%,70%,100% {
        transform: scale(1)
    }

    100% {
        opacity: 0
    }
}
```
