### ISSUE TITLE
Do not remove units from 0 in the flex property

### ISSUE THREAD

**Issue by ghost** [css/csso#200]
According to the [spec](http://dev.w3.org/csswg/css-flexbox/#flex-property), the `flex-basis` component of a `flex` property value must have a unit to avoid as a flex factor.  Removing the unit from the `flex-basis` component will cause Internet Explorer to ignore the property.

Correct syntax:

```
flex: 1;        /* flex-grow only */
flex: 0%;       /* flex-basis only */
flex: 1 1;      /* flex-grow + flex-shrink */
flex: 1 0%;     /* flex-grow + flex-basis */
flex: 1 1 0%;   /* flex-grow + flex-shrink + flex-basis */
```

**Comment by ben-eb** [comment]
I can't reproduce this with CSSO. Test case:

```css
h1 {
    flex: 1;      /* flex-grow only */
}

h2 {
    flex: 0%;     /* flex-basis only */
}

h3 {
    flex: 1 1;    /* flex-grow + flex-shrink */
}

h4 {
    flex: 1 0%;   /* flex-grow + flex-basis */    
}

h5 {
    flex: 1 1 0%; /* flex-grow + flex-shrink + flex-basis */
}
```

Seems correctly minified to me:

```css
h1{flex:1}h2{flex:0%}h3{flex:1 1}h4{flex:1 0%}h5{flex:1 1 0%}
```

It's broken in most other minifiers though...

**Comment by lahmatiy** [comment]
Yep, looks like csso doesn't cut `%`. But it cut other units in `flex` that maybe unsafe.

**Comment by abarre** [comment]
Hi, the problem is still happening on `-ms-flex` property : 

csso doesn't seem to fix the problem : 

before : 
```css
.title-bar-right {
  -ms-flex: 1 1 0px;
      flex: 1 1 0px;
}
```

after :
```css
.title-bar-right{-ms-flex:1 1 0;flex:1 1 0px}
```
