### ISSUE TITLE
Transform from/to in @keyframes

### ISSUE THREAD

**Issue by mgol** [css/csso#205]
The following CSS:
```css
@keyframes anim {
	from {
		opacity: 0;
	}
	100% {
		opacity: 1;
	}
}
.class {
	animation: anim 4s linear infinite;
}
```
is transformed by CSSO to:
```css
@keyframes anim{from{opacity:0}100%{opacity:1}}.class{animation:anim 4s linear infinite}
```
You could cut some bytes by changing `from` to `0%` and `100%` to `to`, though.
