### ISSUE TITLE
Partial Merging of blocks is not working properly

### ISSUE THREAD

**Issue by thucxuong** [css/csso#225]
When i tried to minify a css file with CSSO. the partial merging feature doesn't work right though the properties of those block are the same number of character.

```css
.icon-arrow {
  background-image: url(sprite.png);
  background-position: -80px 0px;
  width: 75px;
  height: 24px;
}
.icon-logo {
  background-image: url(sprite.png);
  background-position: 0px -80px;
  width: 68px;
  height: 88px;
}
.icon-play {
  background-image: url(sprite.png);
  background-position: 0px 0px;
  width: 80px;
  height: 80px;
}

```
The expected result is to group all background url into one block but it only group the last two, while the first one is ignore.

```css
.icon-arrow{background-image:url(sprite.png);background-position:-80px 0;width:75px;height:24px}.icon-logo{background-position:0 -80px;width:68px;height:88px}.icon-logo,.icon-play{background-image:url(sprite.png)}.icon-play{background-position:0 0;width:80px;height:80px}
```

Please help to check it out.

**Comment by lahmatiy** [comment]
csso 1.6 outputs (formated):

```css
.icon-arrow,.icon-logo,.icon-play {
    background-image: url(sprite.png);
    background-position: -80px 0;
    width: 75px;
    height: 24px
}

.icon-logo,.icon-play {
    background-position: 0 -80px;
    width: 68px;
    height: 88px
}

.icon-play {
    background-position: 0 0;
    width: 80px;
    height: 80px
}
```
