### ISSUE TITLE
Wrong optimization of transform rule

### ISSUE THREAD

**Issue by ikokostya** [css/csso#227]
Before:

```css
.foo {
  transform: translate(-50%, -50%);
  transform: translate3d(-50%, -50%, 0);
}
```

After optimizations: 

```css
.foo{transform:translate3d(-50%,-50%,0)}
```

This rule doesn't work properly in Opera 12.x
