### ISSUE TITLE
Structural optimization fails on browser hacks

### ISSUE THREAD

**Issue by asapach** [css/csso#231]
Reproducible on Bootstrap 3.3.5:
```css
.caret {
  border-top: 4px dashed;
  border-top: 4px solid \9;
}
```
Optimized:
```css
.caret {
  border-top: 4px solid \9;
}
```
The IE8 browser hack breaks the other declaration.
