### ISSUE TITLE
Don't merge properties with fallback values

### ISSUE THREAD

**Issue by lahmatiy** [css/csso#241]
Most common cases:

```css
.foo
{
  font-size: 10px;
  font-size: 1rem;
}
```

```css
.foo
{
  filter: url(blur.svg#blur);
  filter: blur(5px);
}
```

**Comment by lahmatiy** [comment]
One more issue (#231):

```css
.caret {
  border-top: 4px dashed;
  border-top: 4px solid \9;
}
```
