### ISSUE TITLE
Invalid css is generated when children selectors are present

### ISSUE THREAD

**Issue by codereverser** [css/csso#246]
In v1.4.0 , the css to select all descendants of an element, say for example
```css
div.dropdown * {
   color: #ff0000;
}
```

gets converted to an invalid css

```css
div.dropdown*{color:red}
```

instead of 

```css
div.dropdown *{color:red}
```
whereas v1.3.12 converts it just fine.
