### ISSUE TITLE
Restructuring large files leads to wrong CSS

### ISSUE THREAD

**Issue by DennisBecker** [css/csso#248]
CSSO 1.4.1
    nodejs 0.12.7

I have a project which Bootstrap 3.3.5 with Sass and there are some points where default Bootstrap styles are overwritten in other files, like the color for the a tag. 

You see something like the following in the CSS file within a browser before CSSO:

```css
// styles.css line 15538
a {
    color: #004b7d;
    text-decoration: underline;
}

// styles.css line 403
a {
    color: #428bca;
    text-decoration: none;
}
```

After CSSO with restructuring the following is found in the resulting CSS file:
```css
a {
    color: #428bca;
    text-decoration: none;
}
```

That's the defintion which is earlier in the file (line 409) instead of the defintion from line 15538.

This issue started with version 1.4.0. I'm using grunt-csso which still uses the csso.justDoIt() method. Don't know if this is a problem for now.

I try to find a test.css file that reproduces this missbehaviour and will add this to this issue.
