### ISSUE TITLE
Removal of overridden properties not work with background-color

### ISSUE THREAD

**Issue by kisonic** [css/csso#257]
Before:
```css
.test {
  background-color: #fff;
  background-color: #000;
  color: red;
  margin: 0;
  line-height: 3cm;
  color: green;
}
```

After:
```css
.test {
  background-color: #fff;
  background-color: #000;
  margin: 0;
  line-height: 3cm;
  color: green
}
```

**Comment by lahmatiy** [comment]
Yep. For now `csso` [avoids to merge any background properties](https://github.com/css/csso/blob/master/lib/compressor/index.js#L899) since it's too complex and leads to bugs. I'm planing to improve property merge after next big release.

**Comment by kisonic** [comment]
Ok, thanks!

**Comment by lahmatiy** [comment]
Current output (formatted):

```css
.test {
    background-color: #000;
    margin: 0;
    line-height: 3cm;
    color: green
}
```

So it's not an issue now.
