### ISSUE TITLE
Incorrect minification of @supports

### ISSUE THREAD

**Issue by vbwdev** [css/csso#258]
This code

```css
@supports ((-webkit-filter: invert(1)) or (filter: invert(1))) {
  a:hover {
    -webkit-filter: invert(1);
            filter: invert(1);
  }
}
```

is minimized in this code

```css
@supports ((-webkit-filter:invert(1))or (filter:invert(1))){a:hover{-webkit-filter:invert(1);filter:invert(1)}}
```

Сhrome and Firefox don't work without space between ")" and "or".

It works correctly http://jsfiddle.net/hgfn04xq/
It works incorrectly http://jsfiddle.net/tcq6fsbp/
