### ISSUE TITLE
Хак для Оперы

### ISSUE THREAD

**Issue by vitaliyzolotoy** [css/csso#26]
После такого невалидного хака для оперы, в процессе оптимизации, CSSO теряет все следующие после него стили.

``` css
/* Opera 9.5 > */ /* */
@media all and (resolution = 0dpi)
{
   #js:root .b-form-checkbox__bg 
   {
      background: #fff;
   }
   #js:root .b-form-checkbox
   {
      background: #9a9a9a;
   }
}
```

(Opera >= 9.5 и < 10.50 [stackoverflow](http://stackoverflow.com/questions/4079738/how-do-i-hide-css-from-opera-10-0-and-earlier))
