### ISSUE TITLE
Incorrect optimization - overrides file order 

### ISSUE THREAD

**Issue by davidmfoley** [css/csso#264]
We have this:
```css
.notification-banner.drop {
    top: -50px
}

.notification-banner.drop.in {
    top: 0
}

.notification-banner.drop.out {
    top: -50px
}

```
which is optimized incorrectly to:
```css
.notification-banner.drop,.notification-banner.drop.out {
    top: -50px
}

.notification-banner.drop.in {
    top: 0
}
```

This was working with v1.4.4 and is broken in v1.5.1

**Comment by shuhrat** [comment]
+1

**Comment by lahmatiy** [comment]
csso v1.5.2 with fix is out

**Comment by shuhrat** [comment]
thank you

**Comment by shuhrat** [comment]
does not seems to work (
```css
.input__found {
    position: absolute;
    z-index: 1;
    display: none;
    padding-left: 4px;
    white-space: nowrap;
    line-height: 32px;
    color: #bbb;
}

.input__found_visibility_visible {
    display: block;
}

.input_requery_yes .input__found,
.input_focused_yes .input__found {
    display: none;
}
```
optimized as

```css
.input__found {
    color: #bbb;
    line-height: 32px;
    padding-left: 4px;
    position: absolute;
    white-space: nowrap;
    z-index: 1;
}
.input__found_visibility_visible {
    display: block;
}
.input__found, .input_focused_yes .input__found, .input_requery_yes .input__found {
    display: none;
}
```
