### ISSUE TITLE
Add support for flags in attribute selector

### ISSUE THREAD

**Issue by lahmatiy** [css/csso#270]
This CSS cause to parse error, but shouldn't.

```css
[foo=bar i] {
    test: 123;
}
```

https://www.w3.org/TR/selectors4/#attribute-case
