### ISSUE TITLE
Fails on counters style sheet

### ISSUE THREAD

**Issue by radiocity** [css/csso#271]
Style:
```css
li:before{
    content: counters(item, ".") + "."; /* browsers work perfectly but csso*/
    counter-increment: item;
}
```
Error log:
```bash
D:\...\csso\lib\parser\index.js:115
    throw new Error('Please check the validity of the CSS block starting from th
e line #' + currentBlockLN);
    ^

Error: Please check the validity of the CSS block starting from the line #485
    at throwError (D:\...\csso\lib\parser\index.js:115:11)
    at getBlock (D:\...\csso\lib\parser\index.js:523:14)
    at getRuleset (D:\...\csso\lib\parser\index.js:1595:18)
    at getStylesheet (D:\...\csso\lib\parser\index.js:1797:52)
    at Object.CSSPRules.stylesheet (D:\...\csso\lib\parser\index.js:80:65)
    at parse (D:\...\csso\lib\parser\index.js:2108:30)
    at Object.minify (D:\...\csso\lib\index.js:33:15)
    at Transform.stream._transform (D:\...\gulp-csso\index.js:23:34)
    at Transform._read (_stream_transform.js:166:10)
    at Transform._write (_stream_transform.js:154:12)
```
Honestly, I use csso as a part of gulp-csso wrapper
