### ISSUE TITLE
Rules with attribute selector with flags shouldn't to be merged with others

### ISSUE THREAD

**Issue by lahmatiy** [css/csso#291]
```css
.foo[a=b] {
  color: red;
}
span[a=b i] {
  color: red;
}
```

Current output (formatted):
```css
.foo[a=b],
span[a=b i] {
  color: red;
}
```

Should be:

```css
.foo[a=b] {
  color: red;
}
span[a=b i] {
  color: red;
}
```

Since only edge browsers support for flags in attribute selector.
