### ISSUE TITLE
Using first property, of the same kind, if the later uses calc

### ISSUE THREAD

**Issue by AntonTrollback** [css/csso#297]
```css
.foo {
  padding: 0;
  padding: calc(1px + 1px);
}
/* .foo { padding: 0; } */

.bar {
  padding: 0;
  padding: 2px;
}
/* .bar { padding: 2px; } */
```

Happens for multi value properties such as `padding`, `margin`, `border-width`, etc.

**Comment by lahmatiy** [comment]
```css
.foo {
  padding: 0;
  padding: calc(1px + 1px);
}
```

Expected

```css
.foo{padding:0;padding:calc(1px + 1px)}
```

Actual

```css
.foo{padding:0}
```
