### ISSUE TITLE
Merge font-faces with similar font-* rules

### ISSUE THREAD

**Issue by a-x-** [css/csso#298]
Merge
```css
        @font-face {
            font-family: 'Yandex Sans Text Web';
            font-weight: 300;
            font-style: normal;
            font-stretch: normal;

            src: url(Yandex-Sans-Text-Web-Bold.woff) format('woff');
        }

        @font-face {
            font-family: 'Yandex Sans Text Web';
            font-weight: 300;
            font-style: normal;
            font-stretch: normal;

            src: url(Yandex-Sans-Text-Web-Bold.woff2) format('woff2');
        }
```

into (reverse urls!):

```css
        @font-face {
            font-family: 'Yandex Sans Text Web';
            font-weight: 300;
            font-style: normal;
            font-stretch: normal;

            src: url(Yandex-Sans-Text-Web-Bold.woff2) format('woff2'), url(Yandex-Sans-Text-Web-Bold.woff) format('woff');
        }

```

algorithm suggestion:
1. make hash by font-* rules predicate, create clusters
2. match&join urls in clusters

**Comment by zxqfox** [comment]
Hm...

I'd say into:
```css
        @font-face {
            font-family: 'Yandex Sans Text Web';
            font-weight: 300;
            src: url(Yandex-Sans-Text-Web-Bold.woff2) format('woff2');
        }
```

What you suggest is not the same for browsers.
