### ISSUE TITLE
Wrong partial merge when ruleset has overlaping properties with same specificity

### ISSUE THREAD

**Issue by lahmatiy** [css/csso#304]
```css
.a .b {
    opacity: 1;
}
.foo {
    opacity: 0;
    color: #ff0000;
}
.bar {
    opacity: 1;
    display: block;
}
```

Expected

```css
.a .b {
    opacity: 1;
}
.foo {
    opacity: 0;
    color: #ff0000;
}
.bar {
    opacity: 1;
    display: block;
}
```

Actual

```css
.a .b, .bar {
    opacity: 1
}

.foo {
    opacity: 0;
    color: red
}

.bar {
    display: block
}
```

Moving up `opacity` from `.bar` is wrong here since `.foo` will override it.
