### ISSUE TITLE
minfiy with restructure removes duplicate cursor

### ISSUE THREAD

**Issue by bgotink** [css/csso#306]
I'm using something like this

```css
.drag-and-drop__handle {
  cursor: url('cursors/grag.cur'), move;
  cursor: grab;
}

.drag-and-drop--dragging .drag-and-drop__handle {
  cursor: url('cursors/grabbing.cur'), move;
  cursor: grabbing;
}
```

to add a grab/grabbing cursor to a drag and drop handle. We need the `url(...)` fallback for IE and Edge, which don't support the `grab`/`grabbing` cursors.

CSSO minification (with restructuring enabled) removes the first cursor line, which breaks the experience for IE.
I can use a workaround with two classes, each containing one cursor, but then the code readability incurs a loss. Would it be possible to add some way to explicitly allow _some_ duplicate CSS properties? (e.g. by allowing all duplicate `cursor`s using configuration or using comment directives cf. `/* csso: ignore duplicate */` to allow duplicates on a case per case basis)
