### ISSUE TITLE
Missing space breaks shorthand border-color in IE

### ISSUE THREAD

**Issue by slackero** [css/csso#310]
I have seen this issue (CSS triangle) under IE9 (Windows 7) and IE11 (Windows 7/10).

The missing space between `rgba()transparent` breaks the style.

![bildschirmfoto 2016-07-23 um 08 51 09](https://cloud.githubusercontent.com/assets/15139/17076494/ff153c18-50b3-11e6-8c01-ab0483799eaf.png)
![bildschirmfoto 2016-07-23 um 08 51 41](https://cloud.githubusercontent.com/assets/15139/17076495/0103a136-50b4-11e6-9543-eae80839f7df.png)

**Input:**
```CSS
.nav-main > li > .nav-sub > li.active:after {
  position: absolute;
  bottom: -28px;
  left: 15px;
  right: 0;
  margin-left: auto;
  margin-right: auto;
  content: '';
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 0 16px 16px 16px;
  border-color: transparent transparent rgba(238, 239, 240, 0.93) transparent;
  -webkit-animation: fadeIn 2s;
  animation: fadeIn 2s;
  -webkit-animation-fill-mode: forwards;
          animation-fill-mode: forwards;
}
```

**Result:**
```CSS
.nav-main>li>.nav-sub>li.active:after{position:absolute;bottom:-28px;left:15px;right:0;margin-left:auto;margin-right:auto;content:'';width:0;height:0;border-style:solid;border-width:0 16px 16px;border-color:transparent transparent rgba(238,239,240,.93)transparent;-webkit-animation:fadeIn 2s;animation:fadeIn 2s;-webkit-animation-fill-mode:forwards;animation-fill-mode:forwards
```

**Working/expected:**
```CSS
.nav-main>li>.nav-sub>li.active:after{position:absolute;bottom:-28px;left:15px;right:0;margin-left:auto;margin-right:auto;content:'';width:0;height:0;border-style:solid;border-width:0 16px 16px;border-color:transparent transparent rgba(238,239,240,.93) transparent;-webkit-animation:fadeIn 2s;animation:fadeIn 2s;-webkit-animation-fill-mode:forwards;animation-fill-mode:forwards
```

I have tried http://css.github.io/csso/csso.html too – there it seems to work well.
