### ISSUE TITLE
Wrong structural optimization of border-color

### ISSUE THREAD

**Issue by lahmatiy** [css/csso#311]
Test case

```css
.foo { 
  border-color: red;
  border-right-color: blue;
}
```

Expected
```css
.foo{border-color:red blue red red}
```

Actual
```css
.foo{border-color:red}
```

`blue` is just cut off. And something strange here since if replace `blue` for incorrect color keyword (e.g. `blu`) ok become correct.
```css
.foo{border-color:red;border-right-color:blu}
```

**Comment by toptalo** [comment]
Have still this issue:

Source
```css
.foo {
      border: 18px solid white;
      border-right-color: transparent;
      border-bottom-color: transparent;
}
```
Expected
```css
.foo {border:18px solid #fff;border-right-color:transparent;border-bottom-color:transparent;}
```
Actual
```css
.foo {border:18px solid #fff;}
```
seme effect with `rgba(0,0,0,0)`


But if I set
```css
.foo {
      border: 18px solid white;
      border-right-color: rgba(255,255,255,0);
      border-bottom-color: rgba(255,255,255,0);
}
```
I've got
```css
.foo {border:18px solid #fff;border-right-color:rgba(255,255,255,0);border-bottom-color:rgba(255,255,255,0);}
```
