### ISSUE TITLE
Optimizing and Collapsing inside a media query

### ISSUE THREAD

**Issue by bob005** [css/csso#314]
consider the following.
```CSS
@media screen and (min-width:1400px)
{
    .container,.container-fluid
    {
        padding-left: 25px;
        padding-right: 25px;
    }

    .container
    {
        width: 1400px;
    }

    .row
    {
        margin-left: -25px;
        margin-right: -25px;
    }

    .col-xl-1
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 8.33333333%;
    }

    .col-xl-offset-1,.col-xl-push-1
    {
        margin-left: 8.33333333%;
    }

    .col-xl-pull-1
    {
        margin-left: -8.33333333%;
    }

    .col-xl-2
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 16.66666667%;
    }

    .col-xl-offset-2,.col-xl-push-2
    {
        margin-left: 16.66666667%;
    }

    .col-xl-pull-2
    {
        margin-left: -16.66666667%;
    }

    .col-xl-3
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 25%;
    }

    .col-xl-offset-3,.col-xl-push-3
    {
        margin-left: 25%;
    }

    .col-xl-pull-3
    {
        margin-left: -25%;
    }

    .col-xl-4
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 33.33333333%;
    }

    .col-xl-offset-4,.col-xl-push-4
    {
        margin-left: 33.33333333%;
    }

    .col-xl-pull-4
    {
        margin-left: -33.33333333%;
    }

    .col-xl-5
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 41.66666667%;
    }

    .col-xl-offset-5,.col-xl-push-5
    {
        margin-left: 41.66666667%;
    }

    .col-xl-pull-5
    {
        margin-left: -41.66666667%;
    }

    .col-xl-6
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 50%;
    }

    .col-xl-offset-6,.col-xl-push-6
    {
        margin-left: 50%;
    }

    .col-xl-pull-6
    {
        margin-left: -50%;
    }

    .col-xl-7
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 58.33333333%;
    }

    .col-xl-offset-7,.col-xl-push-7
    {
        margin-left: 58.33333333%;
    }

    .col-xl-pull-7
    {
        margin-left: -58.33333333%;
    }

    .col-xl-8
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 66.66666667%;
    }

    .col-xl-offset-8,.col-xl-push-8
    {
        margin-left: 66.66666667%;
    }

    .col-xl-pull-8
    {
        margin-left: -66.66666667%;
    }

    .col-xl-9
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 75%;
    }

    .col-xl-offset-9,.col-xl-push-9
    {
        margin-left: 75%;
    }

    .col-xl-pull-9
    {
        margin-left: -75%;
    }

    .col-xl-10
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 83.33333333%;
    }

    .col-xl-offset-10,.col-xl-push-10
    {
        margin-left: 83.33333333%;
    }

    .col-xl-pull-10
    {
        margin-left: -83.33333333%;
    }

    .col-xl-11
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 91.66666667%;
    }

    .col-xl-offset-11,.col-xl-push-11
    {
        margin-left: 91.66666667%;
    }

    .col-xl-pull-11
    {
        margin-left: -91.66666667%;
    }

    .col-xl-12
    {
        display: block;
        box-sizing: border-box;
        float: left;
        padding-left: 25px;
        padding-right: 25px;
        width: 100%;
    }

    .col-xl-offset-12,.col-xl-push-12
    {
        margin-left: 100%;
    }

    .col-xl-pull-12
    {
        margin-left: -100%;
    }
}
```
Now csso does not collapse the codes for some reason. it only minifies it by stripping spacs and newlines. I think it could be a bug or it might be my misunderstanding of csso. please clarify or fix as needed.
