### ISSUE TITLE
maxk-box-image css property results in error

### ISSUE THREAD

**Issue by annamalai-saro** [css/csso#317]
```css
.test {
    background: -webkit-gradient(linear, left top, left bottom, from(rgba(0, 0, 0, .2)), to(rgba(0, 0, 0, 0)));
    -webkit-mask-box-image: -webkit-gradient(linear, left top, right top, color-stop(, rgba(0, 0, 0, 0)), color-stop(.5, rgba(0, 0, 0, .8)), color-stop(1, rgba(0, 0, 0, 0)))
}
```

results in error

`Error : Cannot read property 'sequence' of null`
