### ISSUE TITLE
Add support for ::slotted() pseudo-element

### ISSUE THREAD

**Issue by jarek-foksa** [css/csso#319]
`::slotted()` is a valid CSS pseudo-element selector that was introduced by Custom Elements / Shadow DOM v1. It is currently defined by https://drafts.csswg.org/css-scoping/#slotted-pseudo. 

CSSO should not throw parse errors when `::slotted()` is used, for example:

```css
::slotted(h3) {
  font-size: 30px;
}
```
