### ISSUE TITLE
background:url is put in the wrong order and overrides background-repeat

### ISSUE THREAD

**Issue by batiste** [css/csso#326]
.ric-logo-404 {
  background-image:url('./images/404.png');
  background-repeat: no-repeat;
  background-size: contain;
  background-position: right bottom;
  min-height:290px;
}

.ric-logo-500 {
  background-image:url('./images/500.png');
  background-repeat: no-repeat;
  background-size: contain;
  background-position: right bottom;
  min-height:290px;
}

Generate this

.ric-logo-500{background-repeat:no-repeat;background-size:contain;background-position:right bottom;min-height:290px}.ric-logo-404{background:url(./images/404.png)}.ric-logo-500{background:url(./images/500.png)}

Which seems to simple override the values...

**Comment by lahmatiy** [comment]
What version do you use? I tried your example with last version (via [web interface](https://css.github.io/csso/csso.html)) and result looks correct:

```css
.ric-logo-404,.ric-logo-500{background-image:url(./images/404.png);background-repeat:no-repeat;background-size:contain;background-position:right bottom;min-height:290px}.ric-logo-500{background-image:url(./images/500.png)}
```
