### ISSUE TITLE
Strange restructurization of properties

### ISSUE THREAD

**Issue by underoot** [css/csso#337]
I've this stylesheet:

```
.block__elem1 {
	width: 100%;
	height: 100%;
	display: flex;

        padding: 20px;
}

.block__elem2 {
	width: 20rem;
        color: #fff;
}

.block__elem2 {
	width: 100%;
        height: 100%;
	display: flex;
}
```

After converting it through CSSO with _restructure_ enabled I have:
```
.block__elem1,.block__elem2 {
    width: 100%;
    height: 100%;
    display: flex
}

.block__elem1 {
    padding: 20px
}

.block__elem2 {
    width: 20rem;
    color: #fff
}
```

But expected:
```
.block__elem1,.block__elem2 {
    width: 100%;
    height: 100%;
    display: flex
}

.block__elem1 {
    padding: 20px
}

.block__elem2 {
    color: #fff
}
```

**Comment by lahmatiy** [comment]
You're right. The reason of this behaviour a `rem` unit used for `block_elem2`. `rem` unit (and some other) has different support across browsers, therefore it doesn't mix with other unit.
After first step (initialMergeRuleset) we get just two rules:

```css
.block__elem1 {
    width: 100%;
    height: 100%;
    display: flex;
    padding: 20px
}

.block__elem2 {
    width: 20rem;
    color: #fff;
    width: 100%;
    height: 100%;
    display: flex
}
```

Since `width` property for `block__elem2` has two values with different support it doesn't merge. On last step (restructRuleset) rules are merging and we get a result you've provided. It's not a just non-optimal minification, but also wrong transformation that's break original CSS. So it's a bug actually.

There are few related issues. I'm going to fix it but can't give a promise when. Sorry.

Anyway, your example would be useful. Thank you.
