### ISSUE TITLE
Merge identical font-face rules

### ISSUE THREAD

**Issue by peterbe** [css/csso#351]
I put a block like this:
```css
@font-face {
  font-family: Glyphicons Halflings;
  src: url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot);
  src: url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot?#iefix) format('embedded-opentype'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.448c34a5.woff2) format('woff2'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.fa277232.woff) format('woff'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.e18bbf61.ttf) format('truetype'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.89889688.svg#glyphicons_halflingsregular) format('svg')
}
@font-face {
  font-family: Glyphicons Halflings;
  src: url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot);
  src: url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot?#iefix) format('embedded-opentype'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.448c34a5.woff2) format('woff2'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.fa277232.woff) format('woff'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.e18bbf61.ttf) format('truetype'), url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.89889688.svg#glyphicons_halflingsregular) format('svg')
}
```

I'm trying to minimize this so it only appears once. 
```
> fs.readFile('hack.fontfaces.css', (err, buf) => {
... let css = buf.toString()
... console.log(csso.minify(css).css)
... })
undefined
```

The output is (when line broken manually):
```
@font-face{
font-family:Glyphicons Halflings;src:url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot);src:url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot?#iefix) format('embedded-opentype'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.448c34a5.woff2) format('woff2'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.fa277232.woff) format('woff'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.e18bbf61.ttf) format('truetype'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.89889688.svg#glyphicons_halflingsregular) format('svg')}
@font-face{
font-family:Glyphicons Halflings;src:url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot);src:url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.f4769f9b.eot?#iefix) format('embedded-opentype'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.448c34a5.woff2) format('woff2'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.fa277232.woff) format('woff'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.e18bbf61.ttf) format('truetype'),url(https://songsearch-2916.kxcdn.com/static/media/glyphicons-halflings-regular.89889688.svg#glyphicons_halflingsregular) format('svg')}
```
