### ISSUE TITLE
Remove word-break fallback value

### ISSUE THREAD

**Issue by SuperOl3g** [css/csso#365]
Same problem with #281 and #278 
[CSS-tricks recommend](https://css-tricks.com/almanac/properties/w/word-break/#article-header-id-0) adding fallback value for IE.

Input
```css
div { 
      word-break: break-all;
     /* Non standard for WebKit */
     word-break: break-word;
}
```

Output 
```css
div { 
     word-break: break-word;
}
```

Expected 
```css
div { 
      word-break: break-all;
     /* Non standard for WebKit */
     word-break: break-word;
}
```

**Comment by Finesse** [comment]
Another fallback example that mustn't be collapsed:

```css
.bar {
  overflow: auto;
  overflow: overlay;
}
```
