### ISSUE TITLE
Merges prefixed placeholder selectors incorrectly

### ISSUE THREAD

**Issue by Zashy** [css/csso#383]
This seems to be merging prefixed placeholder selectors incorrectly. Was working on a site using csso and it broke for IE11. The following two selectors are being merged which would be okay, but IE11 just chokes on the double colon `::` and doesn't parse the style. For further details check out the [issue over on cssnano](https://github.com/cssnano/cssnano/issues/419).

```CSS
input:-ms-input-placeholder {
  color: transparent;
}
input::-ms-input-placeholder {
  color: transparent;
}
```
Is merged into the following, which breaks IE11:
```CSS
input:-ms-input-placeholder, input::-ms-input-placeholder {
  color: transparent;
}
```

Adding `{ restructure: false }` does work as a workaround for now.
