### ISSUE TITLE
restructure - issue on csso-cli 3.5.1 (with the smallest code possible)

### ISSUE THREAD

**Issue by mr21** [css/csso#384]
Hi :)

This code:
``` css
.a {
	display: flex;
	box-sizing: border-box;
	transition: .3s;
	transition-property: color, background;
}

.b {
	display: flex;
	box-sizing: border-box;
	transition: inherit;
}
```
output this:
``` css
.a,.b{display:flex;box-sizing:border-box}.a{transition-property:color,background;transition:.3s}.b{transition:inherit}
```
(prettify here)
``` css
.a, .b {
	display: flex;
	box-sizing: border-box;
}
.a {
	transition-property: color, background;
	transition: .3s;
}
.b {
	transition: inherit;
}
```

The problem is the order of properties after the restructuration, the `transition` overwrite the `transition-property`.
