### ISSUE TITLE
calc() causes incorrect re-ordering

### ISSUE THREAD

**Issue by ThomasBrierley** [css/csso#385]
CSSO appears to treat properties with `calc()` in the value as separate:

```css
/* input */
div {
	width: 0;
	width: calc(100px);
}
```

```css
/* output */
div {
	width: 0;
	width: calc(100px)
}
```

Unfortunately this causes more than missed optimisation opportunities:

```css
/* input */
div, .foo {
	height: 0;
	width: 0;
}
div {
	height: 0;
	width: calc(100px);
}
```

```css
/* output */
div {
	width: calc(100px)
}
.foo, div {
	height: 0;
	width: 0
}
```

### Environment
- csso: v3.5.1
- node: v8.11.3
