### ISSUE TITLE
Better merging for same-name-selectors 

### ISSUE THREAD

**Issue by asakasinsky** [css/csso#400]
Hello!
I'm a little confused :-)
 
Input styles:

```css
.awesome {
  border: 1px solid green;
  padding: 5px 20px;
}
.some-user-class {
  color: green;
}
.awesome {
  font-size: 14px;
}

```
Output styles (via https://css.github.io/csso/csso.html):
```css
.awesome {
    border: 1px solid green;
    padding: 5px 20px
}

.some-user-class {
    color: green
}

.awesome {
    font-size: 14px
}
```

What  expected:
```css
.awesome {
    border: 1px solid green;
    padding: 5px 20px;
    font-size: 14px
}

.some-user-class {
    color: green
}
```
