### ISSUE TITLE
Wrong restructuring of height in class and element selectors

### ISSUE THREAD

**Issue by accetone** [css/csso#411]
Please check following input and output. Class `layout` will have `height: 60px` which is incorrect.

Input
```css
html {
  width: 100%;
  height: 100%;
  margin: 0;
}

.header {
  width: 100%;
  height: 60px;
}

.layout {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
}
```

Output
```css
.layout,
html {
  height: 100%;
  margin: 0
}

html {
  width: 100%
}

.header,
.layout {
  width: 100%;
  height: 60px
}

.layout {
  padding: 0
}
```
