### ISSUE TITLE
Unexpected exception caused by an invalid declaration value

### ISSUE THREAD

**Issue by Finesse** [css/csso#412]
For example, an error message for such code (a result of incorrect usage of Stylus):

```css
.foo {
  width: 14px;
  margin-right: -@width;
}
```

Is `undefined is not an object (evaluating 'e.value.children.some')`.

I have to do some tricks to find what causes the error (the real CSS is much bigger), it's inconvenient. I expect either to get no error (CSSO just leaves unknown property values as is) or to get a reference to the bad CSS code in the error message.
