### ISSUE TITLE
Wrong restructuring of border rules

### ISSUE THREAD

**Issue by accetone** [css/csso#417]
Tested with 4.0.3.

Maybe duplicate of #143, but I'm not 100% sure, so decide to create new issue.

Here is example.

```css
// Input
.class1 {
    border-bottom: 1px solid black;
}

.class2 {
    border: 0;
    border-bottom: 1px solid black;
}

.class3 {
    border: 0;
}
```

```css
// Output
.class1,.class2{
  border-bottom:1px solid #000
}

.class2,.class3{
  border:0
}
```

The problem is that `border-bottom` overwritted by `border` which not the case in source style.
