### ISSUE TITLE
Incorrect `padding` optimization (CSS variables problem)

### ISSUE THREAD

**Issue by dizel3d** [css/csso#420]
```css
.foobar {
  padding: var(--button-size-m-text-indentAll);
  padding-right: var(--button-size-m-icon-indentRight);
}
```
becomes
```css
.foobar {
  padding: var(--button-size-m-text-indentAll) var(--button-size-m-icon-indentRight) var(--button-size-m-text-indentAll) 
  var(--button-size-m-text-indentAll);
}
```
It's incorrect for
```css
--button-size-m-text-indentAll: 0 20px;
--button-size-m-icon-indentRight: 30px;
```
