### ISSUE TITLE
Doesn't optimize custom properties

### ISSUE THREAD

**Issue by dizel3d** [css/csso#422]
```js
require('csso').minify(text).css
```

where `text` equals
```css
:root {
    --color-controls-type-action-typo-base: rgba(0, 0, 0, 0.1);
    --color-controls-type-action-fill-color-base: rgb(235, 225, 224);
}
```

returns
```css
:root{--color-controls-type-action-typo-base: rgba(0, 0, 0, 0.1);--color-controls-type-action-fill-color-base: rgb(235, 225, 224)}
```

but expected
```css
:root{--color-controls-type-action-typo-base:rgba(0,0,0,.1);--color-controls-type-action-fill-color-base:#ebe1e0}
```
