### ISSUE TITLE
Media query order with forceMediaMerge:true

### ISSUE THREAD

**Issue by davidhirtz** [css/csso#424]
I would love to have an option to define the media query order when the `forceMediaMerge` is `true`. Currently I setup all media queries on the top of the CSS with an unused element in the order I need (for example mobile first):

```css
@media (min-width: 375px) {
  ._ {
    width: 375px;
  }
}

@media (min-width: 415px) {
  ._ {
    width: 415px;
  }
}
```

This is an ok solution but it creates unnecessary declarations. I tried to create empty media queries with `/*! ... */` comments, but those get stripped inside media queries even with `comments` set `true` and thus will not preserve the correct order.

Is there a better solution? Thank you very much!
