### ISSUE TITLE
Add support for CSS variable replacement

### ISSUE THREAD

**Issue by Jaeiya** [css/csso#425]
Before conversion
```css
root: {
  --red: #ff0000;
}
.myclass { color: --red; }
```

After conversion
```css
.myclass { color: #ff0000; }
```
I have a very large file with all the variables inside it for theme management; it would be nice to remove all those long names and just replace them with the colors. It would save a huge amount of space.
