### ISSUE TITLE
Bug with re-ordering statements

### ISSUE THREAD

**Issue by jacobp100** [css/csso#429]
#### Input

```css
.test {
  font: inherit;
  font-size: 14px;
}

.other {
  color: red;
  font-size: 14px;
}
```

#### Output (Formatted)

```css
.other, .test {
  font-size: 14px;
}

.test {
  font: inherit;
}

.other {
  color: red;
}
```

Before `.test` had `font-size: 14px`, and now it has `font-size: inherit`.

**Comment by gscanlon21** [comment]
To give another example, I also see this happening when restructuring the output of one of foundation-sites header styles mixin:
##### **`input`**
```css
div,
dl,
dt,
dd,
ul,
ol,
li,
h1,
h2,
h3,
h4,
h5,
h6,
pre,
form,
p,
blockquote,
th,
td {
  margin: 0;
  padding: 0;
}

h1, .h1 {
  font-size: 3rem;
  line-height: 0.9;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

h2, .h2 {
  font-size: 4.6875rem;
  line-height: 0.8666666667;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

h3, .h3 {
  font-size: 2rem;
  line-height: 1.0625;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

h4, .h4 {
  font-size: 1.625rem;
  line-height: 1.0769230769;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

h5, .h5 {
  font-size: 1rem;
  line-height: 1.125;
  margin-top: 0;
  margin-bottom: 0.5rem;
}

h6, .h6 {
  font-size: 0.875rem;
  line-height: 1.2142857143;
  margin-top: 0;
  margin-bottom: 0.5rem;
}
```

##### **`Output`**
```css
blockquote,dd,div,dl,dt,form,li,ol,p,pre,td,th,ul {
    margin: 0;
    padding: 0
}

h1,h2,h3,h4,h5,h6 {
    padding: 0
}

.h1,h1 {
    font-size: 3rem;
    line-height: .9
}

.h1 {
    margin-top: 0
}

h1,h2 {
    margin: 0
}

.h1,.h2,.h3,h1,h2,h3 {
    margin-bottom: .5rem
}

.h2,h2 {
    font-size: 4.6875rem;
    line-height: .8666666667
}

.h2 {
    margin-top: 0
}

.h3,h3 {
    font-size: 2rem;
    line-height: 1.0625
}

h3 {
    margin: 0
}

.h3 {
    margin-top: 0
}

.h4,h4 {
    font-size: 1.625rem;
    line-height: 1.0769230769
}

.h4 {
    margin-top: 0
}

h4,h5 {
    margin: 0
}

.h4,.h5,.h6,h4,h5,h6 {
    margin-bottom: .5rem
}

.h5,h5 {
    font-size: 1rem;
    line-height: 1.125
}

.h5 {
    margin-top: 0
}

.h6,h6 {
    font-size: .875rem;
    line-height: 1.2142857143
}

h6 {
    margin: 0
}

.h6 {
    margin-top: 0
}
```

Before, all the header elements had `margin-bottom: 0.5rem`. Now there is no `margin-bottom: 0.5rem` for `h3` or `h6`
