### ISSUE TITLE
Restructuring Removes Background Image Trick

### ISSUE THREAD

**Issue by jmwebservices** [css/csso#431]
For UAs not supporting SVG as background images, there is a nice fallback which CSSO restructuring destroys.
```css
.selector
{
    background-image: url( 'image.png' );
    background-image: url( 'image.svg' ), none;
}
```

Results in:
```css
.selector {
    background-image: url(image.svg),none
}
```
