### ISSUE TITLE
Is there a way to remove duplication of properties in the `@media`?

### ISSUE THREAD

**Issue by cawa-93** [css/csso#440]
I would like to configure compiling of css with different theme configurations so as to avoid duplicating common properties.

Test case:
```css
.foo {
    color: red;
    padding: 10px;
}

@media(prefers-color-scheme: dark) {
    .foo {
        color: tomato;
        padding: 10px;
    }
}
```

Actual output:
```css
.foo {
    color: red;
    padding: 10px
}

@media (prefers-color-scheme:dark) {
    .foo {
        color: tomato;
        padding: 10px
    }
}
```

Expected output:
```css
.foo {
    color: red;
    padding: 10px
}

@media (prefers-color-scheme:dark) {
    .foo {
        color: tomato;
        /* no more padding */
    }
}
```
