### ISSUE TITLE
csso v5 whitespace might be broken 

### ISSUE THREAD

**Issue by barak007** [css/csso#447]
input

```css
.foo { border: 1px solid "PLACEHOLDER"; }
```

I know that in this example the value of border is not valid css value. 
But in our case we have a post-process that will replace the "PLACEHOLDER" with a real value later and in the new version of csso it removes the space before the `"`

it will become 

```css
.foo { border: 1px solid"placeholder"; }
```

I know it's related to `css-tree` upgrade, any chances that we could preserve this space?
