### ISSUE TITLE
Merging is broken for :where selectors

### ISSUE THREAD

**Issue by ygoe** [css/csso#454]
[`:where()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:where) selectors have zero specificity so their order is the only thing that matters. csso will merge multiple selectors into a single comma-separated selector if they have the same content. But then, it will also change their order and it renders differently in browsers.

Example SASS:

```scss
:where(a)
{
	&:where(:link)
	{
		text-decoration: underline;
		:where(.stop) &
		{
			text-decoration: revert;
		}

		&:where(:hover, :focus)
		{
			text-decoration: none;
			:where(.stop) &
			{
				text-decoration: revert;
			}
		}
	}
}
```

Compiled to CSS:

```css
:where(a):where(:link) {
  text-decoration: underline;
}
:where(.stop) :where(a):where(:link) {
  text-decoration: revert;
}
:where(a):where(:link):where(:hover, :focus) {
  text-decoration: none;
}
:where(.stop) :where(a):where(:link):where(:hover, :focus) {
  text-decoration: revert;
}
```

Result after csso: (inserted line breaks for readability)

```css
:where(a):where(:link){text-decoration:underline}
:where(.stop) :where(a):where(:link),:where(.stop) :where(a):where(:link):where(:hover, :focus){text-decoration:revert}
:where(a):where(:link):where(:hover, :focus){text-decoration:none}
```

If anything, the second line needs to come last (merge to last occurrence, not to first). But then again, it's still a different order than declared in the source.

Similar to #301?
