### ISSUE TITLE
Contents of the :is and :where pseudo-class functions is not optimized

### ISSUE THREAD

**Issue by pepelsbey** [css/csso#458]
I’m using CSSO via postcss-csso v6.0.0 that uses csso 5.0.1, but the same applies when I run my code via the [online version](http://css.github.io/csso/csso.html) with v5.0.4.

Here’s the code after compression, you can clearly see the untouched parts inside of the `:is`:

```css
.header__button{position:relative;z-index:2}.header__button[aria-expanded=false] :is(
    .header__icon-close,
    .header__text-close
),.header__button[aria-expanded=true] :is(
    .header__icon-menu,
    .header__text-menu
){display:none}.header__link{display:inline-block;border-radius:50%;color:var(--color-text-primary)}
```

<details>
<summary>Code before compression</summary>

```css
/* Button */

.header__button {
    position: relative;
    z-index: 2;
}

.header__button[aria-expanded='false'] :is(
    .header__icon-close,
    .header__text-close
) {
    display: none;
}

.header__button[aria-expanded='true'] :is(
    .header__icon-menu,
    .header__text-menu
) {
    display: none;
}

/* Link */

.header__link {
    display: inline-block;
    border-radius: 50%;
    color: var(--color-text-primary);
}
```

</details>

The same happens with `:where`, but `:not` content gets optimized.

How it looks If you replace `:is` with `:not`:

```css
.header__button{position:relative;z-index:2}.header__button[aria-expanded=false] :not(.header__icon-close,.header__text-close),.header__button[aria-expanded=true] :not(.header__icon-menu,.header__text-menu){display:none}.header__link{display:inline-block;border-radius:50%;color:var(--color-text-primary)}
```

I see `:is` and `:where` mentioned in [v5.0.0 release notes](https://github.com/css/csso/releases/tag/v5.0.0) as supported, but probably not fully supported.
