### ISSUE TITLE
Wrong border compressed result when with shorthand-border

### ISSUE THREAD

**Issue by shinken008** [css/csso#462]
```css
.no-border {
    border: 0 solid transparent;
    border-width: 1px;
}

.red-border {
    border: 0 solid red;
    border-width: 1px;
}
```
will be transformed:
```css
.no-border,.red-border {
    border: 0 solid transparent;
    border-width: 1px
}

.red-border {
    border: 0 solid red
}
```
`.red-border`'s property `border-width` is gone.
