### ISSUE TITLE
Duplicate content property removed 

### ISSUE THREAD

**Issue by JDrizzy** [css/csso#471]
The content property allows for an alternative text value which is [not supported in Firefox and Safari](https://developer.mozilla.org/en-US/docs/Web/CSS/content#browser_compatibility). A library that I'm using works around this issue by including a [content value twice](https://github.com/DataTables/DataTablesSrc/commit/949852472e3b396eb48d6249d62e9e8d027bb1c0). This is to ensure a sort icon is always displayed regardless of browser support.

Using the latest version of CSSO (`5.0.5`) breaks this icon display for all browsers since the duplicate content value is removed.

Input
```CSS
.test:before {
  content: "▲";
  content: "▲"/"";
}
```

Output
```Css
.test:before{content:"▲"/""}
```
Expected
```CSS
.test:before{content:"▲";content:"▲"/""}
```
