### ISSUE TITLE
Add support for CSS Nesting

### ISSUE THREAD

**Issue by freshp86** [css/csso#474]
See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting.

It currently seems to not work and nested CSS rules are stripped from the output. For example passing the following

```css
.parent {
 & .child {
  color: blue;
 }
}
```
produces an empty output. Same happens if the `&` nesting selector is omitted.
