### ISSUE TITLE
A bug with restructuring and shorthands

### ISSUE THREAD

**Issue by stoyan** [css/csso#478]
```css
.a {
    background: none;
    background-size: 1;
    b: c;
}

.b {
    background: some;
    background-size: 1;
    b: c;
}
```

becomes 

```css
.a,.b {
    background-size: 1;
    b: c
}

.a {
    background: 0 0
}

.b {
    background: some
}
```

The problem is `background-size` is wiped out by the shorthand `background` that comes after it
