### ISSUE TITLE
Минификация множественных значений фонов

### ISSUE THREAD

**Issue by kizu** [css/csso#58]
Скажем, если есть что-то такое:

``` CSS
.class {
    background: url(1.png) 100% 100% no-repeat,
                url(2.jpg) 100% 100% no-repeat,
                url(3.jpg) 100% 100% no-repeat,
                url(4.jpg) 100% 100% no-repeat;
}
```

То это не самый оптимальный вариант как это можно описать: в подобных случаях можно вынести все повторяющиеся значения в начало, а неповторяющиеся — описать после. Получится что-то такое (отформатированное):

``` CSS
.class {
    background: 100% 100% no-repeat;
    background-image: url(1.png),
                      url(2.jpg),
                      url(3.jpg),
                      url(4.jpg);
}
```

Экономия: из 142 в 104 символа в этом конкретном случае. Подозреваю, что чем дальше тем больше люди будут использовать множественные фоны и градиенты, так что можно будет подумать в эту сторону.

Это, в принципе, относится к части уже описанных вариантов сжатия шортхендов, но я решил отдельным пунктом упомянуть :) Ну и да — это совсем не критично и, скорее, можно будет делать когда остальные возможности по оптимизации будут исчерпаны.
