### ISSUE TITLE
Structure optimization of multiple (3 and more) mutual rules

### ISSUE THREAD

**Issue by p4tient** [css/csso#65]
Consider the following code:

``` css
a { width: 1%; margin: 0 auto; padding: 1em; }
b { width: 2%; margin: 0 auto; padding: 1em; }
c { width: 3%; margin: 0 auto; padding: 1em; }
```

With the current implementation the resulting CSS is far from optimal:

``` css
a { width: 1%; margin: 0 auto; padding: 1em }
b { width: 2% }
b, c { margin: 0 auto; padding: 1em }
c { width: 3% }
```

It would be nice to become something like this instead:

``` css
a { width: 1% }
b { width: 2% }
c { width: 3% }
a, b, c { margin: 0 auto; padding: 1em }
```

**Comment by lahmatiy** [comment]
Current result is
```css
a,b,c {
    width: 1%;
    margin: 0 auto;
    padding: 1em
}
b,c {
    width: 2%
}
c {
    width: 3%
}
```

It's much better and correct, but redundant `c` in 2nd ruleset.
