### ISSUE TITLE
Optimization: remove quotes surrounding font family names when possible

### ISSUE THREAD

**Issue by mathiasbynens** [css/csso#72]
Input:

``` css
x {
  font-family: "Comic Sans MS";
}
```

Current output:

``` css
x{font-family:"Comic Sans MS"}
```

It could be just:

``` css
x{font-family:Comic Sans MS}
```

See http://mathiasbynens.be/notes/unquoted-font-family for all the details.
