### ISSUE TITLE
Optimization: remove quotes surrounding attribute values in attribute selectors when possible

### ISSUE THREAD

**Issue by mathiasbynens** [css/csso#73]
Input:

```css
x[lol="wat"] {
  x: y;
}
```

Current output:

```css
x[lol="wat"] {
  x: y;
}
```

In this case, it could be:

```css
x[lol=wat] {
  x: y;
}
```

See http://mathiasbynens.be/notes/unquoted-attribute-values for all details.
