### ISSUE TITLE
Неправильная структурная минификации margin

### ISSUE THREAD

**Issue by dfilatov** [css/csso#76]
Исходный css:

``` css
.test1{margin-top:0}
.test2{margin-top:100px}
.test1{margin-left:0}
.test1{margin-bottom:0}
.test1{margin-right:0}
```

После минификации:

``` css
.test2{margin-top:100px}.test1{margin:0}
```

Если применить исходный и миницифированный варианты к такому html:

``` html
<div class="test1 test2"></div>
```

То получим разные результаты:
- при применении исходного css, div будет иметь результирующий верхний отступ 100px
- при применении минифицированного варианта css, div будет иметь результирующий верхний отступ 0

Ожидаемый результат:

``` css
.test1{margin-top:0}.test2{margin-top:100px}.test1{margin-left:0;margin-bottom:0;margin-right:0}
```
