### ISSUE TITLE
Bug: no minification happens to shorthand when throwing away non-important style

### ISSUE THREAD

**Issue by kizu** [css/csso#78]
When there are important styles that can be minified to a shorthand, but there is also a non-important style along with them, it is thrown away, but the shorthand is not created:

``` CSS
.foo {
    margin-top: 0 !important;
    margin-right: 0 !important;
    margin-bottom: 0 !important;
    margin-left: 0 !important;
    margin-top: 0;
}
```

is minified now to

``` CSS
.foo{margin-top:0!important;margin-right:0!important;margin-bottom:0!important;margin-left:0!important}
```

So, running CSSO here for the second time minifies the left properties properly.
