### ISSUE TITLE
Bug: Keyframe optimization blocks 0% keyframe, prevents animation from running

### ISSUE THREAD

**Issue by restlessdesign** [css/csso#80]
Discovered this while using the [Animate.css](http://daneden.me/animate/) library. Only using the `-webkit-` prefix to keep this example short:

```css
@-webkit-keyframes rotateInUpRight {
  0% {
    -webkit-transform-origin: right bottom;
    -webkit-transform: rotate(-90deg);
    opacity: 0;
  }

  100% {
    -webkit-transform-origin: right bottom;
    -webkit-transform: rotate(0);
    opacity: 1;
  }
}
```

Gives the following output (expanded for readability):

```css
@-webkit-keyframes rotateInUpRight{
    0% {
        -webkit-transform:rotate(-90deg);
        opacity:0
    }
    
    0%,100% {
        -webkit-transform-origin:right bottom;
    }
    
    100%{
        -webkit-transform:rotate(0);
        opacity:1
    }
}
```

The issue is caused by the `0%,100%` keyframe appearing **after** the `0%` keyframe declaration. Altered, this code will animate as expected:

```css

@-webkit-keyframes rotateInUpRight{
    0%,100% {
        -webkit-transform-origin:right bottom;
    }

    0% {
        -webkit-transform:rotate(-90deg);
        opacity:0
    }

    100%{
        -webkit-transform:rotate(0);
        opacity:1
    }
}
```
