### ISSUE TITLE
Don't remove similar properties with vendor values

### ISSUE THREAD

**Issue by afelix** [css/csso#81]
I think this is a similar issue:

``` css
div {
    height: -webkit-calc(100% - 30px);
    height: -moz-calc(100% - 30px);
    height: -ms-calc(100% - 30px);
    height: -o-calc(100% - 30px);
    height: calc(100% - 30px);
}
```

minimized:

``` css
div{height:calc(100% - 30px)}
```
