### ISSUE TITLE
csso 1.3.2 compresses ".t-1" and ".t-01" as identical classes

### ISSUE THREAD

**Issue by doochik** [css/csso#88]
``` css
.t-1
{
color: red;
}

.t-01
{
color: blue;
}
```

actual result

``` css
.t-1{color:#00f}
```

valid result

``` css
.t-1{color:#f00}.t-01{color:#00f}
```
